### PR TITLE
Adjustments and Fixes (i.e. compiler warnings)

### PR DESCRIPTION
**Pull request by Luc4sQ**
Notes:

- I've implemented an eventHandler, an update function, a render function and a scale algorithm for the visuals as pleased from @Ung0d .

- I've implemented a better trouble detection for program arguments and combined my GraphRenderer with a state.

- I've solved all compiler warnings

- I've tried to follow the coding conventions and made few doxygen comments for the documentation

- I've made some optimizations in terms of dublicated code

But: I've merged the branch **graph**, so it just works with the new data structures

### CODE REVIEW

**Comment by Luc4sQ** [comment]
I've forgot:

I've wrote some optimizations in terms of dublicated code.

**Comment by MarioStanke** [comment]
The build fails as can be seen when clicking on the Travis CI results:
```
g++ -c -std=c++11 -Wall  ../GraphRenderer.cc -o GraphRenderer.o
../GraphRenderer.cc: In member function ‘void GraphRenderer::drawText(sf::RenderWindow&)’:
../GraphRenderer.cc:199:14: error: ‘class sf::Text’ has no member named ‘setFillColor’
         text.setFillColor(txt[i].col);
```
Can you fix that?

**Comment by Luc4sQ** [comment]
Das ist komisch. Auf der sfml Seite existiert der Member und mein Compiler wollte sogar, dass ich diese Funktion statt der setColor() funktion nutze.

https://www.sfml-dev.org/documentation/2.5.1/classsf_1_1Text.php#ab7bb3babac5a6da1802b2c3e1a3e6dcc

Soll ich sie trotzdem ersetzen?

**Comment by MarioStanke** [comment]
Verstehe. Bei mir (Ubuntu 18.04) kompiliert es auch. Die alte Version von SFML kannte offenbar setFillColor noch nicht. Leider gibt es bei Travis-CI noch nicht die Option ein Bionic Beaver (Ubuntu 18.04) image zu nehmen. Fuer den commit lassen wir einmal setFillColor und koennen nachher eine Loesung fuer das CI besprechen.

**Comment by MarioStanke** [comment]
This branch has conflicts that must be resolved. Please merge the current origin/master into sDt4_VisualFixes and reopen pull request.

**Pull request closed without merging**
