### PR TITLE
Feature/sLt2 gamemaster

### PR DESCRIPTION
**Pull request by TimonKapischke**
- add a class Gamemaster
- this class create a Graph, a State and a vector of DrawNodes for given parameters
- change the SequenceSimulation Code: I add a new function simulate(). The function contains a big part of the code from the old main function. 
- add the code from StaticGraph/main.cc into GUI_main.cc
- I use the "master" version of Graphrenderer (updated soon)
- the scrolling from the rendered Graph doesn't work (it works only without Buttons)

### CODE REVIEW

**Comment by Ung0d** [comment]
* I think the GameMaster files should be moved to MAS/src. You could also create a gameMain.cpp or something like that creates a game master and renders a graph. (use the already existing Makefile in MAS/src)
* You could combine this with your existing GUI and add functionality to the "play" button: Create a `GameMaster` object and use the GraphRenderer to render the graph

**Comment by Ung0d** [comment]
@MoritzGrillo @sebastianbierb @mauricerad  Once Timon has the file "gameMain.cc" created, you could add your existing `Agent` with a `RandomPolicy` to it. A first prototype for the game could look like this:
* Player and Agent have each their own state and consecutively select egdes (Player can select edges with a mouse click)
* The current score for player and agent are both displayed (@TimonKapischke ? )

**Comment by TimonKapischke** [comment]
The score isn't displayed yet, but soon.

**Comment by TimonKapischke** [comment]
- fix bug with the scrolling
- rename GUI_main.cc into gameMain.cc

**Comment by TimonKapischke** [comment]
- add a folder GameMain in src
- update makefiles
- delete GUI
- move button.cc and button.h into visualization

**Comment by Ung0d** [comment]
Thanks

**Pull request merged**
