### PR TITLE
Feature/alignment state

### PR DESCRIPTION
**Pull request by mauricerad**

### CODE REVIEW

**Comment by mauricerad** [comment]
Mainly worked on criticism [here](https://mslehre.github.io/MAS/md_docs_April15.html), I have left out making a struct to combine the three vectors of same length, because i have yet to be sure what the final graph structure is going to be like.

Included doxygen comments to the best of my knowledge and aligned my code with:
https://github.com/mslehre/MAS/wiki/Coding-Conventions
https://github.com/mslehre/MAS/wiki/Documentation-with-Doxygen
https://github.com/mslehre/MAS/issues/24

**Comment by Ung0d** [comment]
Thanks. Please stick to the new directory structure src/*. Your files fit in src/alignment/*. The graph will be there as well. Also, please put your test-code and the corresponding makefile in another subdirectory over there. In the makefile you can access files in higher directories like so: "../State.cpp"

**Comment by Ung0d** [comment]
Should be an one-liner using git mv (https://git-scm.com/docs/git-mv). Make sure your #includes in the source code match the new format

**Comment by Ung0d** [comment]
I have checked your code logically. Your tests seem to work (I checked only a few edges from your edgelist and compared the output). Good job so far.

In your `select(int i)` method, you call `updateSelectability()` which then iterates over the whole edgelist. I don't think this is necessary at this point if you assume that the current selection is consistent. You just have to check consistency in terms of the new edge i (from select(i)) and not in terms of all edges. It is sufficient to find the edges that are crossed by the new edge i and set "selectable" to false for them. Then none of these edges can be selected in the future.

**Comment by mauricerad** [comment]
Thanks for the advice. I have moved the files to the src directory.

As for your efficiency suggestion, have you taken into account that, in the actual game, edges don't have to be chosen in any particular order? As far as I'm aware, your change would only work in the current version but would have to be reverted as soon as any edge could be chosen at any time as long as it is selectable.

**Comment by Ung0d** [comment]
I will merge now, since it basically works. We can discuss further changes in class.

**Pull request merged**
