### PR TITLE
Feature/sLt1 button

### PR DESCRIPTION
**Pull request by TimonKapischke**
- Makefile with common.mk
- I use std::function now
- delete binarys

I have the problem that I don't know how to pass different function typs with one function call. (void, int, ....)

### CODE REVIEW

**Comment by Ung0d** [comment]
Depends on what you mean. Can you give an example?

**Comment by TimonKapischke** [comment]
int test1() { ...} 
void test2() {...}

Button startButton = Button("Button1.png", 100, 100, test1);
Button startButton = Button("Button2.png", 200, 100, test2);

Maybe we need other functions for the buttons. Not only void functions.

**Comment by TimonKapischke** [comment]
It works with different construktors but how can I define Button_function in button.h?

**Comment by Ung0d** [comment]
We can use lambda expressions (https://en.cppreference.com/w/cpp/language/lambda):
`std::function<void()> func = [graph] () { do something with graph }`
They can capture objects or refs to objects ([] brackets) while the function itself has no arguments.

**Comment by TimonKapischke** [comment]
- I add a new function create_level()
- changes in Makefiles
- rename button.cc and button.h

The create_level() function don't work yet. I can call the SequenceSimulation program but the program doesn't return a FASTA file. I don't know why...  Mayby the system call.

**Comment by Ung0d** [comment]
Why has `Button` a `create_level` method? 
I wouldn't use system. Just include the Sequence Simulation code as usual. Or simply use fasta files produced externally.

**Comment by Ung0d** [comment]
Thanks

**Pull request merged**
